import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, useWindowDimensions, View } from 'react-native';
import type { CatalogItem, ReportEmployee, ReportFilters } from '../domain/contracts';
import { errorMessage, formatSqlDate, reportHtml, todayIso } from '../application/formatters';
import { kioskApi } from '../infrastructure/api';
import { ActionButton, Field, Message, Panel } from './components';
import { colors } from './theme';
import { ReceiptSecuritySettings } from './ReceiptSecuritySettings';

export function ReportsScreen({ onBack, onPhotos }: { onBack(): void; onPhotos(): void }) {
  const { width, height } = useWindowDimensions();
  const portrait = height > width;
  const today = todayIso();
  const [from, setFrom] = useState(today), [to, setTo] = useState(today);
  const [payrolls, setPayrolls] = useState<CatalogItem[]>([]), [payrollCodes, setPayrollCodes] = useState<string[]>([]);
  const [dependencies, setDependencies] = useState<CatalogItem[]>([]), [dependencyCodes, setDependencyCodes] = useState<string[]>([]);
  const [employees, setEmployees] = useState<ReportEmployee[]>([]), [employeeCodes, setEmployeeCodes] = useState<string[]>([]);
  const [search, setSearch] = useState(''), [includeExit, setIncludeExit] = useState(false);
  const [rows, setRows] = useState<Record<string, unknown>[]>([]), [showReport, setShowReport] = useState(false);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState<string | null>(null);
  const filters = (): ReportFilters => ({ from: formatSqlDate(from), to: formatSqlDate(to), payrollCodes, dependencyCodes, search: search || undefined });
  const run = async (work: () => Promise<void>) => { setBusy(true); setMessage(null); try { await work(); } catch (caught) { setMessage(errorMessage(caught)); } finally { setBusy(false); } };
  const loadPayrolls = () => void run(async () => { const data = await kioskApi.reports.payrolls(); setPayrolls(data); setPayrollCodes(data.map(x => x.code)); });
  const loadDependencies = () => void run(async () => { if (!payrollCodes.length) throw new Error('Seleccione al menos una nómina.'); const data = await kioskApi.reports.dependencies(payrollCodes); setDependencies(data); setDependencyCodes(data.map(x => x.code)); });
  const loadEmployees = () => void run(async () => { if (!dependencyCodes.length) throw new Error('Seleccione al menos una dependencia.'); const data = await kioskApi.reports.employees(filters()); setEmployees(data); setEmployeeCodes(data.map(x => String(x.Codigo))); });
  const generate = () => void run(async () => { if (!employeeCodes.length) throw new Error('Seleccione al menos un empleado.'); const data = await kioskApi.reports.generate({ ...filters(), search: undefined, employeeCodes, includeExitTime: includeExit }); setRows(data); setShowReport(true); });
  const exportPdf = () => void run(async () => { if (!rows.length) return; const { uri } = await Print.printToFileAsync({ html: reportHtml(rows) }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Exportar reporte de asistencia' }); });
  const columns = useMemo(() => rows.length ? Object.keys(rows[0]) : [], [rows]);
  return <View style={styles.page}><View style={[styles.header, portrait && styles.headerPortrait]}><ActionButton icon="arrow-back" label="Volver" secondary onPress={onBack} /><Ionicons name="bar-chart" size={28} color={colors.navy} /><View style={styles.headerTitle}><Text style={styles.title}>Seguridad de RRHH</Text><Text style={styles.muted}>Reportes de asistencia y fotografías</Text></View><ActionButton icon="camera" label="Actualizar foto" secondary onPress={onPhotos} disabled={busy} /><ActionButton icon="options" label="Filtros" secondary onPress={() => setShowReport(false)} /><ActionButton icon="document-text" label={`Reporte (${rows.length})`} onPress={() => setShowReport(true)} /></View>
    <ReceiptSecuritySettings />
    {!showReport ? <ScrollView contentContainerStyle={styles.content}><View style={[styles.columns, portrait && styles.columnsPortrait]}><Panel style={[styles.filters, portrait && styles.fullWidth]}><Text style={styles.heading}>Rango de fechas</Text><Text style={styles.label}>Fecha inicial (AAAA-MM-DD)</Text><Field value={from} onChangeText={setFrom} /><Text style={styles.label}>Fecha final (AAAA-MM-DD)</Text><Field value={to} onChangeText={setTo} /><Text style={styles.heading}>Nóminas</Text><ActionButton icon="download" label="Cargar nóminas" onPress={loadPayrolls} disabled={busy} /><Checklist items={payrolls} selected={payrollCodes} onChange={setPayrollCodes} /><Text style={styles.heading}>Dependencias</Text><ActionButton icon="download" label="Cargar dependencias" onPress={loadDependencies} disabled={busy} /><Checklist items={dependencies} selected={dependencyCodes} onChange={setDependencyCodes} /></Panel>
      <Panel style={styles.employees}><View style={styles.toolbar}><View><Text style={styles.heading}>Empleados</Text><Text style={styles.muted}>{employees.length} encontrados</Text></View><ActionButton icon="people" label="Cargar empleados" onPress={loadEmployees} disabled={busy} /></View><Field value={search} onChangeText={setSearch} placeholder="Buscar por nombre, apellido o código" /><ScrollView style={styles.employeeList}>{employees.map((row, i) => { const code = String(row.Codigo); return <CheckRow key={`${code}-${i}`} selected={employeeCodes.includes(code)} label={Object.entries(row).filter(([key]) => key !== 'Seleccionar').map(([, value]) => String(value ?? '')).join(' · ')} onPress={() => setEmployeeCodes(current => current.includes(code) ? current.filter(x => x !== code) : [...current, code])} />; })}</ScrollView><View style={styles.toolbar}><View style={styles.switch}><Switch value={includeExit} onValueChange={setIncludeExit} /><Text>Con hora de salida</Text></View><ActionButton icon="play" label="Generar reporte" onPress={generate} disabled={busy} /></View></Panel></View>{message && <Message text={message} />}</ScrollView> : <View style={styles.report}><View style={styles.toolbar}><View><Text style={styles.heading}>Entrada/Salida de Empleados</Text><Text style={styles.muted}>{rows.length} registros</Text></View><ActionButton icon="share" label="Exportar PDF" onPress={exportPdf} disabled={!rows.length || busy} /></View><ScrollView horizontal style={{ flex: 1 }}><ScrollView><View><View style={styles.tableRow}>{columns.map(column => <Text key={column} style={[styles.cell, styles.head]}>{column}</Text>)}</View>{rows.map((row, i) => <View key={i} style={styles.tableRow}>{columns.map(column => <Text key={column} style={styles.cell}>{String(row[column] ?? '')}</Text>)}</View>)}</View></ScrollView></ScrollView>{message && <Message text={message} />}</View>}
  </View>;
}
function Checklist({ items, selected, onChange }: { items: CatalogItem[]; selected: string[]; onChange(value: string[]): void }) { return <View>{items.map(item => <CheckRow key={item.code} label={item.description} selected={selected.includes(item.code)} onPress={() => onChange(selected.includes(item.code) ? selected.filter(x => x !== item.code) : [...selected, item.code])} />)}</View>; }
function CheckRow({ label, selected, onPress }: { label: string; selected: boolean; onPress(): void }) { return <Pressable onPress={onPress} style={styles.checkRow}><Ionicons name={selected ? 'checkbox' : 'square-outline'} size={22} color={selected ? colors.green : colors.muted} /><Text style={{ flex: 1, color: colors.ink }}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg }, header: { minHeight: 78, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', padding: 12, gap: 12, backgroundColor: '#fff', borderBottomWidth: 1, borderColor: colors.line }, headerPortrait: { flexWrap: 'wrap' }, headerTitle: { flex: 1, minWidth: 180 }, title: { fontSize: 21, fontWeight: '800', color: colors.ink }, muted: { color: colors.muted }, content: { padding: 16, gap: 10 }, columns: { flexDirection: 'row', gap: 14 }, columnsPortrait: { flexDirection: 'column' }, filters: { width: 310, gap: 8 }, fullWidth: { width: '100%' }, employees: { flex: 1, gap: 10 }, heading: { fontSize: 18, fontWeight: '800', color: colors.ink, marginTop: 5 }, label: { color: colors.muted, fontSize: 12 }, toolbar: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, employeeList: { maxHeight: 300, borderWidth: 1, borderColor: colors.line, borderRadius: 10 }, checkRow: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 9, borderBottomWidth: 1, borderColor: colors.line }, switch: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  report: { flex: 1, padding: 16, gap: 10 }, tableRow: { flexDirection: 'row' }, cell: { width: 150, padding: 7, borderRightWidth: 1, borderBottomWidth: 1, borderColor: '#ccd5da', backgroundColor: '#fff', fontSize: 11 }, head: { backgroundColor: colors.navy, color: '#fff', fontWeight: '800' }
});
