export const faceEngineHtml = `<!doctype html>
<html><head><meta name="viewport" content="width=device-width"><style>html,body{margin:0;background:#07151d;color:#fff;font:14px Arial}body{display:grid;place-items:center;height:100%}</style></head>
<body><span id="status">Cargando motor facial…</span><script src="/api/face-assets/face-api.min.js"></script><script>
const post=(type,data={})=>window.ReactNativeWebView&&window.ReactNativeWebView.postMessage(JSON.stringify({type,...data}));
let reference=null,threshold=.52,required=3,matches=0,phase='identity',baseline=0,turned=false,ready=false,busy=false;
const opts=()=>new faceapi.TinyFaceDetectorOptions({inputSize:224,scoreThreshold:.5});
const yaw=landmarks=>{const jaw=landmarks.getJawOutline(),nose=landmarks.getNose();const width=Math.max(Math.hypot(jaw[0].x-jaw[16].x,jaw[0].y-jaw[16].y),.001);return(nose[3].x-(jaw[0].x+jaw[16].x)/2)/width};
async function image(value){const img=new Image();img.src=value;await img.decode();return img}
async function initialize(message){threshold=message.threshold||.52;required=message.required||3;const result=await faceapi.detectSingleFace(await image(message.reference),opts()).withFaceLandmarks().withFaceDescriptor();if(!result)throw new Error('La fotografía registrada no contiene un rostro reconocible.');reference=result.descriptor;ready=true;post('ready')}
async function verify(value){if(!ready||busy)return;busy=true;try{const faces=await faceapi.detectAllFaces(await image(value),opts()).withFaceLandmarks().withFaceDescriptors();if(faces.length!==1){matches=0;post('progress',{status:faces.length>1?'Solo debe aparecer una persona':'Ubique su rostro dentro del marco',matches,phase});return}const face=faces[0];const distance=faceapi.euclideanDistance(reference,face.descriptor);if(distance>threshold){matches=0;post('progress',{status:'El rostro no coincide con la fotografía registrada',matches,phase,distance});return}const current=yaw(face.landmarks);if(phase==='identity'){matches++;post('progress',{status:'Confirmando identidad '+matches+'/'+required,matches,phase,distance});if(matches>=required){baseline=current;phase='turn';post('progress',{status:'Gire la cabeza hacia un lado',matches,phase,distance})}}else if(phase==='turn'){if(Math.abs(current-baseline)>.09){turned=true;phase='center';post('progress',{status:'Vuelva al centro',matches,phase,distance})}else post('progress',{status:'Gire un poco más la cabeza',matches,phase,distance})}else if(phase==='center'&&turned){if(Math.abs(current-baseline)<.045)post('verified',{distance});else post('progress',{status:'Vuelva al centro',matches,phase,distance})}}catch(error){post('error',{message:error.message||String(error)})}finally{busy=false}}
async function receive(event){try{const message=JSON.parse(event.data);if(message.type==='initialize')await initialize(message);if(message.type==='frame')await verify(message.image)}catch(error){post('error',{message:error.message||String(error)})}}
document.addEventListener('message',receive);window.addEventListener('message',receive);
Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri('/api/face-assets/models'),faceapi.nets.faceLandmark68Net.loadFromUri('/api/face-assets/models'),faceapi.nets.faceRecognitionNet.loadFromUri('/api/face-assets/models')]).then(()=>post('models-ready')).catch(error=>post('error',{message:error.message||String(error)}));
</script></body></html>`;
